- name: Create DNS entries for site
  local_action:
    module: route53
    command: create 
    zone: "{{ item.0.zone }}"
    record: "{{ item.1.record }}"
    type: "{{ item.1.type }}"
    ttl: "{{ item.1.ttl }}"
    value: "{{ item.1.value }}"
    overwrite: yes
    profile: "{{ aws_profile }}"
#  with_dict: dns
  with_subelements:
    - "{{ dns }}"
    - entries
